// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMxO_Lqlbb2r9lfoTW9AhLY1Pkn3EZmWg',
    appId: '1:1006580799053:web:67015aa44380fc9669ee04',
    messagingSenderId: '1006580799053',
    projectId: 'instagram-tut-67028',
    authDomain: 'instagram-tut-67028.firebaseapp.com',
    storageBucket: 'instagram-tut-67028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOW8fFXAMkHv0fPzG7bi7XtrCANjsQnJk',
    appId: '1:1006580799053:android:6384f465e199082e69ee04',
    messagingSenderId: '1006580799053',
    projectId: 'instagram-tut-67028',
    storageBucket: 'instagram-tut-67028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1PQXLqXBlXYpMAzysuyUILntXL0-CHE',
    appId: '1:1006580799053:ios:aa2f0dbee95889b569ee04',
    messagingSenderId: '1006580799053',
    projectId: 'instagram-tut-67028',
    storageBucket: 'instagram-tut-67028.appspot.com',
    iosClientId: '1006580799053-nkb0l3j8k5nlqsvmg6jdbq5cvv1ne7bk.apps.googleusercontent.com',
    iosBundleId: 'dre.bsr.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1PQXLqXBlXYpMAzysuyUILntXL0-CHE',
    appId: '1:1006580799053:ios:aa2f0dbee95889b569ee04',
    messagingSenderId: '1006580799053',
    projectId: 'instagram-tut-67028',
    storageBucket: 'instagram-tut-67028.appspot.com',
    iosClientId: '1006580799053-nkb0l3j8k5nlqsvmg6jdbq5cvv1ne7bk.apps.googleusercontent.com',
    iosBundleId: 'dre.bsr.instagramClone',
  );
}
